### ISSUE TITLE
Version alert for undefined constant in WP Admin

### ISSUE THREAD

**Issue by JDevx97** [mattkeys/Advanced-Custom-Fields-Font-Awesome#2]
## Introduction 

Hey Matt, thanks for making a great plugin. Just noticed this and thought I'd drop this in. Not major and looks like an easy fix.

### Details

Just shows up in WP Admin on any page really. 

ACFFA Plugin Version: 3.1.1 
WP Version: 5.2.2
PHP Version: 7.3
Related File: admin/class-ACFFA-Admin.php
Line: 18

> Warning: Use of undefined constant ACFFA_MAJOR_VERSION - assumed 'ACFFA_MAJOR_VERSION' (this will throw an Error in a future version of PHP) in /nas/content/live/seabridgeprod/wp-content/plugins/advanced-custom-fields-font-awesome/admin/class-ACFFA-Admin.php on line 18

<img width="1440" alt="Screen Shot 2019-08-12 at 10 12 22 am" src="https://user-images.githubusercontent.com/36535571/62841288-b2856800-bce9-11e9-854e-d5cb77e39bfb.png">

**Comment by mattkeys** [comment]
Thanks for reporting. I haven't been able to reproduce the issue in my environment yet. In my testing the function that sets this constant is always called before it is later used in class-ACFFA-Admin.php.

Can you share more about which version of Advanced Custom Fields you have installed?

Additionally is there anything odd about the way you have ACF or my plugin installed, perhaps not installed through the plugin manager but instead being included into a theme?

Thanks,

Matt Keys

**Comment by JDevx97** [comment]
Hey man happy too but I'm going to have to kindly apologize here, under further digging found I had two instances of ACFFA, one in mu-plugins and the other in /plugins directory. Entirely my fault and if anything I hope it speaks more to the fact you've made a brilliant plugin. 

Sorry for any time you took out to look into the issue, all the best Matt.

**Comment by mattkeys** [comment]
Okay cool thanks for the update
