### ISSUE TITLE
Combine css with my build tooling

### ISSUE THREAD

**Issue by asha23** [mattkeys/Advanced-Custom-Fields-Font-Awesome#6]
Hi - This is a great plugin!

Is there a simple way I can directly refer to the CSS file so that I can incorporate it into by build process? Currently it loads the fontawesome css separately and this is causing Google Pagespeed insights to nag me :) 

I have found the enqueue script in the plugin itself but I don't really want to remove this. I've also tried dequeuing the stylesheet in my functions file. But this doesn't seem to work.

**Comment by mattkeys** [comment]
You don't have to let this plugin enqueue the FontAwesome CSS on your fronted. When creating your field, there is a yes/no toggle that you can use to turn that off.

From there you should be able to include the FontAwesome CSS in your build process in whatever way makes the most sense to you.
